version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/cd/zip
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationInstall:
    - location: stop.sh # Nginx와 연결되지 않은 프로그램 종료
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start.sh # 열려있는 Port로 새 버전의 Jar파일 실행
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh # 새 프로그램이 정상적인지 확인.
      timeout: 60
      runas: ec2-user